import { questionSchema, type Question } from "./schema";

export const sampleQuestion1: Question = questionSchema.parse({
  schemaVersion: 1,
  id: "sample-001",
  revision: 1,
  status: "draft",
  rulesetVersion: "jp-riichi-4p-v1",
  difficulty: "basic",
  calibrationAxis: "fu",
  context: {
    roundWind: "east",
    seatWind: "south",
    winSource: { kind: "normal", method: "ron" },
    riichi: "riichi",
    ippatsu: false,
  },
  hand: {
    concealed: [
      "1m",
      "2m",
      "3m",
      "4m",
      "5m",
      "6m",
      "7p",
      "8p",
      "9p",
      "2s",
      "3s",
      "4s",
      "5z",
    ],
    melds: [],
    winningTile: "5z",
    doraIndicators: ["1z"],
    uraDoraIndicators: [],
    accessibleDescription:
      "一萬、二萬、三萬、四萬、五萬、六萬、七筒、八筒、九筒、二索、三索、四索、白。白でロン。",
  },
  solution: {
    basis: { kind: "hanFu", han: 1, fu: 40 },
    payment: { kind: "ron", winner: "nonDealer", points: 1300 },
  },
  options: [
    {
      id: "a",
      payment: { kind: "ron", winner: "nonDealer", points: 1300 },
      correct: true,
      diagnosis: {
        assumedHan: 1,
        assumedFu: 40,
        coarseHypotheses: [],
        fineHypotheses: [],
      },
    },
    {
      id: "b",
      payment: { kind: "ron", winner: "nonDealer", points: 2000 },
      correct: false,
      diagnosis: {
        assumedHan: 2,
        assumedFu: 30,
        coarseHypotheses: ["han", "fu"],
        fineHypotheses: [],
      },
    },
    {
      id: "c",
      payment: { kind: "ron", winner: "nonDealer", points: 2600 },
      correct: false,
      diagnosis: {
        assumedHan: 2,
        assumedFu: 40,
        coarseHypotheses: ["han"],
        fineHypotheses: [],
      },
    },
    {
      id: "d",
      payment: { kind: "ron", winner: "nonDealer", points: 3900 },
      correct: false,
      diagnosis: {
        assumedHan: 3,
        assumedFu: 30,
        coarseHypotheses: ["han", "fu"],
        fineHypotheses: [],
      },
    },
  ],
  diagnosis: {
    eligible: true,
    primaryCoarseTarget: "fu",
    fineTargets: ["fu.wait", "fu.rounding"],
    probe: { hanOptions: [1, 2, 3], fuOptions: [30, 40, 50] },
  },
  reviewGroup: ["development-group-a"],
  explanation: {
    summary:
      "白は雀頭なので役牌にはならず、立直1飜です。門前ロンと単騎待ちを含む40符の子ロンとして1,300点です。",
  },
  provenance: {
    author: "development-fixture",
    reviewer: "unreviewed",
    reviewedAt: "not-reviewed",
  },
});

export const sampleQuestion2: Question = questionSchema.parse({
  schemaVersion: 1,
  id: "sample-002",
  revision: 1,
  status: "draft",
  rulesetVersion: "jp-riichi-4p-v1",
  difficulty: "basic",
  calibrationAxis: "han",
  context: {
    roundWind: "east",
    seatWind: "south",
    winSource: { kind: "normal", method: "ron" },
    riichi: "none",
    ippatsu: false,
  },
  hand: {
    concealed: [
      "2m",
      "3m",
      "4m",
      "5m",
      "6m",
      "7m",
      "3p",
      "4p",
      "5p",
      "6s",
      "7s",
      "2s",
      "2s",
    ],
    melds: [],
    winningTile: "8s",
    doraIndicators: ["1z"],
    uraDoraIndicators: [],
    accessibleDescription:
      "二萬、三萬、四萬、五萬、六萬、七萬、三筒、四筒、五筒、六索、七索、二索、二索。八索でロン。",
  },
  solution: {
    basis: { kind: "hanFu", han: 1, fu: 30 },
    payment: { kind: "ron", winner: "nonDealer", points: 1000 },
  },
  options: [
    {
      id: "a",
      payment: { kind: "ron", winner: "nonDealer", points: 1000 },
      correct: true,
      diagnosis: {
        assumedHan: 1,
        assumedFu: 30,
        coarseHypotheses: [],
        fineHypotheses: [],
      },
    },
    {
      id: "b",
      payment: { kind: "ron", winner: "nonDealer", points: 1300 },
      correct: false,
      diagnosis: {
        assumedHan: 1,
        assumedFu: 40,
        coarseHypotheses: ["fu"],
        fineHypotheses: [],
      },
    },
    {
      id: "c",
      payment: { kind: "ron", winner: "nonDealer", points: 1500 },
      correct: false,
      diagnosis: {
        assumedHan: 1,
        assumedFu: 50,
        coarseHypotheses: ["fu"],
        fineHypotheses: [],
      },
    },
    {
      id: "d",
      payment: { kind: "ron", winner: "nonDealer", points: 2000 },
      correct: false,
      diagnosis: {
        assumedHan: 2,
        assumedFu: 30,
        coarseHypotheses: ["han"],
        fineHypotheses: [],
      },
    },
  ],
  diagnosis: {
    eligible: true,
    primaryCoarseTarget: "han",
    fineTargets: ["yaku.presence"],
    probe: { hanOptions: [1, 2, 3], fuOptions: [30, 40, 50] },
  },
  reviewGroup: ["development-group-a"],
  explanation: {
    summary: "断么九（タンヤオ）のみの1飜30符、子のロン和了で1,000点です。",
  },
  provenance: {
    author: "development-fixture",
    reviewer: "unreviewed",
    reviewedAt: "not-reviewed",
  },
});

export const sampleQuestion3: Question = questionSchema.parse({
  schemaVersion: 1,
  id: "sample-003",
  revision: 1,
  status: "draft",
  rulesetVersion: "jp-riichi-4p-v1",
  difficulty: "standard",
  calibrationAxis: "payout",
  context: {
    roundWind: "east",
    seatWind: "east",
    winSource: { kind: "normal", method: "ron" },
    riichi: "riichi",
    ippatsu: false,
  },
  hand: {
    concealed: [
      "1m",
      "2m",
      "3m",
      "4m",
      "5m",
      "6m",
      "7p",
      "8p",
      "9p",
      "5z",
      "5z",
      "5z",
      "3s",
    ],
    melds: [],
    winningTile: "3s",
    doraIndicators: ["1z"],
    uraDoraIndicators: [],
    accessibleDescription:
      "一萬、二萬、三萬、四萬、五萬、六萬、七筒、八筒、九筒、白、白、白、三索。三索でロン。",
  },
  solution: {
    basis: { kind: "hanFu", han: 2, fu: 40 },
    payment: { kind: "ron", winner: "dealer", points: 3900 },
  },
  options: [
    {
      id: "a",
      payment: { kind: "ron", winner: "dealer", points: 2000 },
      correct: false,
      diagnosis: {
        assumedHan: 1,
        assumedFu: 40,
        coarseHypotheses: ["han"],
        fineHypotheses: [],
      },
    },
    {
      id: "b",
      payment: { kind: "ron", winner: "dealer", points: 2900 },
      correct: false,
      diagnosis: {
        assumedHan: 2,
        assumedFu: 30,
        coarseHypotheses: ["fu"],
        fineHypotheses: [],
      },
    },
    {
      id: "c",
      payment: { kind: "ron", winner: "dealer", points: 3900 },
      correct: true,
      diagnosis: {
        assumedHan: 2,
        assumedFu: 40,
        coarseHypotheses: [],
        fineHypotheses: [],
      },
    },
    {
      id: "d",
      payment: { kind: "ron", winner: "dealer", points: 5800 },
      correct: false,
      diagnosis: {
        assumedHan: 3,
        assumedFu: 30,
        coarseHypotheses: ["han", "fu"],
        fineHypotheses: [],
      },
    },
  ],
  diagnosis: {
    eligible: true,
    primaryCoarseTarget: "payout",
    fineTargets: ["context.seat", "payout.table"],
    probe: { hanOptions: [1, 2, 3], fuOptions: [30, 40, 50] },
  },
  reviewGroup: ["development-group-b"],
  explanation: {
    summary: "立直・役牌白の2飜40符、親のロン和了で3,900点です。",
  },
  provenance: {
    author: "development-fixture",
    reviewer: "unreviewed",
    reviewedAt: "not-reviewed",
  },
});

export const sampleQuestion4: Question = questionSchema.parse({
  schemaVersion: 1,
  id: "sample-004",
  revision: 1,
  status: "draft",
  rulesetVersion: "jp-riichi-4p-v1",
  difficulty: "standard",
  calibrationAxis: "fu",
  context: {
    roundWind: "east",
    seatWind: "east",
    winSource: { kind: "normal", method: "ron" },
    riichi: "riichi",
    ippatsu: false,
  },
  hand: {
    concealed: [
      "2m",
      "3m",
      "4m",
      "5m",
      "6m",
      "7m",
      "3p",
      "4p",
      "5p",
      "2s",
      "3s",
      "8s",
      "8s",
    ],
    melds: [],
    winningTile: "4s",
    doraIndicators: ["1z"],
    uraDoraIndicators: [],
    accessibleDescription:
      "二萬、三萬、四萬、五萬、六萬、七萬、三筒、四筒、五筒、二索、三索、八索、八索。四索でロン。",
  },
  solution: {
    basis: { kind: "hanFu", han: 2, fu: 30 },
    payment: { kind: "ron", winner: "dealer", points: 2900 },
  },
  options: [
    {
      id: "a",
      payment: { kind: "ron", winner: "dealer", points: 2000 },
      correct: false,
      diagnosis: {
        assumedHan: 1,
        assumedFu: 40,
        coarseHypotheses: ["han"],
        fineHypotheses: [],
      },
    },
    {
      id: "b",
      payment: { kind: "ron", winner: "dealer", points: 2900 },
      correct: true,
      diagnosis: {
        assumedHan: 2,
        assumedFu: 30,
        coarseHypotheses: [],
        fineHypotheses: [],
      },
    },
    {
      id: "c",
      payment: { kind: "ron", winner: "dealer", points: 3900 },
      correct: false,
      diagnosis: {
        assumedHan: 2,
        assumedFu: 40,
        coarseHypotheses: ["fu"],
        fineHypotheses: [],
      },
    },
    {
      id: "d",
      payment: { kind: "ron", winner: "dealer", points: 4000 },
      correct: false,
      diagnosis: {
        assumedHan: 2,
        assumedFu: 40,
        coarseHypotheses: ["payout"],
        fineHypotheses: [],
      },
    },
  ],
  diagnosis: {
    eligible: true,
    primaryCoarseTarget: "fu",
    fineTargets: ["fu.wait"],
    probe: { hanOptions: [1, 2, 3], fuOptions: [20, 30, 40] },
  },
  reviewGroup: ["development-group-b"],
  explanation: {
    summary: "立直・タンヤオの2飜30符、親のロン和了で2,900点です。",
  },
  provenance: {
    author: "development-fixture",
    reviewer: "unreviewed",
    reviewedAt: "not-reviewed",
  },
});

export const sampleQuestion5: Question = questionSchema.parse({
  schemaVersion: 1,
  id: "sample-005",
  revision: 1,
  status: "draft",
  rulesetVersion: "jp-riichi-4p-v1",
  difficulty: "advanced",
  calibrationAxis: "payout",
  context: {
    roundWind: "east",
    seatWind: "south",
    winSource: { kind: "normal", method: "tsumo" },
    riichi: "riichi",
    ippatsu: false,
  },
  hand: {
    concealed: [
      "1m",
      "2m",
      "3m",
      "4m",
      "5m",
      "6m",
      "7p",
      "8p",
      "9p",
      "5z",
      "5z",
      "5z",
      "2s",
    ],
    melds: [],
    winningTile: "2s",
    doraIndicators: ["1z"],
    uraDoraIndicators: [],
    accessibleDescription:
      "一萬、二萬、三萬、四萬、五萬、六萬、七筒、八筒、九筒、白、白、白、二索。二索でツモ。",
  },
  solution: {
    basis: { kind: "hanFu", han: 3, fu: 40 },
    payment: {
      kind: "nonDealerTsumo",
      winner: "nonDealer",
      nonDealerEach: 1300,
      dealer: 2600,
    },
  },
  options: [
    {
      id: "a",
      payment: {
        kind: "nonDealerTsumo",
        winner: "nonDealer",
        nonDealerEach: 700,
        dealer: 1300,
      },
      correct: false,
      diagnosis: {
        assumedHan: 2,
        assumedFu: 30,
        coarseHypotheses: ["han", "fu"],
        fineHypotheses: [],
      },
    },
    {
      id: "b",
      payment: {
        kind: "nonDealerTsumo",
        winner: "nonDealer",
        nonDealerEach: 1000,
        dealer: 2000,
      },
      correct: false,
      diagnosis: {
        assumedHan: 3,
        assumedFu: 30,
        coarseHypotheses: ["fu"],
        fineHypotheses: [],
      },
    },
    {
      id: "c",
      payment: {
        kind: "nonDealerTsumo",
        winner: "nonDealer",
        nonDealerEach: 1300,
        dealer: 2600,
      },
      correct: true,
      diagnosis: {
        assumedHan: 3,
        assumedFu: 40,
        coarseHypotheses: [],
        fineHypotheses: [],
      },
    },
    {
      id: "d",
      payment: {
        kind: "nonDealerTsumo",
        winner: "nonDealer",
        nonDealerEach: 2000,
        dealer: 4000,
      },
      correct: false,
      diagnosis: {
        assumedHan: 4,
        assumedFu: 40,
        coarseHypotheses: ["han"],
        fineHypotheses: [],
      },
    },
  ],
  diagnosis: {
    eligible: true,
    primaryCoarseTarget: "payout",
    fineTargets: ["context.winMethod", "payout.table"],
    probe: { hanOptions: [2, 3, 4], fuOptions: [30, 40, 50] },
  },
  reviewGroup: ["development-group-a", "development-group-b"],
  explanation: {
    summary:
      "立直・門前清自摸和・役牌白の3飜40符、子のツモ和了で子1,300点・親2,600点です。",
  },
  provenance: {
    author: "development-fixture",
    reviewer: "unreviewed",
    reviewedAt: "not-reviewed",
  },
});

export const sampleQuestions: readonly Question[] = [
  sampleQuestion1,
  sampleQuestion2,
  sampleQuestion3,
  sampleQuestion4,
  sampleQuestion5,
];
